version: "3"
services:
  my_mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME = admin-prakash
      - MONGO_INITDB_ROOT_PASSWORD = password
    volumes:
      - my-mongo-storage:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = admin-prakash
      - ME_CONFIG_MONGODB_ADMINPASSWORD = password
      - ME_CONFIG_MONGODB_SERVER = my_mongo_db

networks:
  default:
    driver: custom-driver

volumes:
  my-mongo-storage:
    driver: local